language: ruby
rvm:
- 1.9.2
- 1.9.3
- 2.0
- 2.1
- 2.2
gemfile:
- gemfiles/rails30.gemfile
- gemfiles/rails31.gemfile
- gemfiles/rails32.gemfile
- gemfiles/rails40.gemfile
- gemfiles/rails41.gemfile
- gemfiles/rails42.gemfile
matrix:
  include:
    - rvm: 1.9.2
      gemfile: gemfiles/ruby192_rails31.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/ruby192_rails32.gemfile
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/rails31.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails41.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails42.gemfile
bundler_args: "--without development"
notifications:
  slack:
    secure: IniiL3PdFsht2zykTwd/z5Et/L1U6GzsmMC1LrgccKCrvLsdcdlBU3VrAgIb1GT9FPEFpb5sl7FEBN80p6uW15uO57onUawFaSWDhSA3eXG1ImmunVPJ20U4NkJvMbnUdZXQ9XXqOw1ggkR7GrD0PM9Nzr4puWaaGq42UJjdaq0=
